name:                servant-auth-wordpress
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/prikhi/wordpress-auth#readme
license:             BSD3
author:              Pavan Rikhi
maintainer:          pavan.rikhi@gmail.com
copyright:           BSD3
category:            Web, Servant
extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - servant-server
  - text
  - time
  - wai
  - wordpress-auth

library:
    source-dirs:      src
