---

name:
    wordpress-auth
version:
    1.0.0.1
synopsis:
    Validate Wordpress Cookies & Nonces; Build Wordpress Hashes & Salts
description: >
    This package is used for validating Cookie data & Nonces from Wordpress.


    You may find it useful if you're trying to serve a Haskell application
    alongside a Wordpress site. By validating the Cookies set by Wordpress, you
    can access the currently logged-in Wordpress user in Haskell without having
    to devise a Wordpress-to-Haskell authentication scheme.


    It includes a generalized authentication function, as well as various
    helpers, validators, & hashers if you'd like to build a custom
    authentication process.


    Servant users may want to just use the @servant-auth-wordpress@ package.
homepage:
    https://github.com/prikhi/wordpress-auth#readme
license:
    BSD3
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    BSD3
category:
    Web
extra-source-files:
    - README.md
    - CHANGELOG.md

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

dependencies:
    - base >= 4.7 && < 5
    - base16-bytestring < 1.1
    - bytestring >= 0.10 && < 0.12
    - cookie ^>= 0.4
    - cryptohash-md5 ^>= 0.11
    - cryptohash-sha256 ^>= 0.11
    - hs-php-session ^>= 0.0.9
    - http-types ^>= 0.12
    - mtl >= 2 && < 3
    - text >= 1 && < 3
    - time >= 1 && < 2
    - uri-encode ^>= 1.5

library:
    source-dirs:
        src
