name:                wordpress-auth
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/prikhi/wordpress-auth#readme
license:             BSD3
author:              Pavan Rikhi
maintainer:          pavan.rikhi@gmail.com
copyright:           BSD3
category:            Web
extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5
  - base16-bytestring
  - bytestring
  - cryptohash-md5
  - cryptohash-sha256
  - hs-php-session
  - text
  - time

library:
    source-dirs:      src
